version: 2
updates:
  - package-ecosystem: cargo
    directories:
      - "/"
      - "wincode"
      - "wincode-derive"
      - "fuzz"
    schedule:
      interval: daily
      time: "08:00"
      timezone: Etc/UTC
    open-pull-requests-limit: 10
